//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Webform_HandsOn
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_Training
    {
        public int Id { get; set; }
        public string Req_Name { get; set; }
        public string Skill { get; set; }
        public System.DateTime Start_D { get; set; }
        public System.DateTime End_D { get; set; }
    }
}
